usr/include/ignition/transport[0-99]/ignition/transport.hh
usr/include/ignition/transport[0-99]/ignition/transport/*.hh
usr/include/ignition/transport[0-99]/ignition/transport/detail/*.hh
usr/lib/*/libignition-transport[0-99].so
usr/lib/*/pkgconfig/ignition-transport[0-99].pc
usr/lib/*/cmake/ignition-transport[0-99]/ignition-transport*
usr/share/ignition/*
usr/lib/ruby/ignition/cmdtransport[0-99].rb
